### ISSUE TITLE
Prettier 2.1.0 and Sass rules with single mixin inclusion

### ISSUE THREAD

**Issue by dappiu** [prettier/prettier#9050]
Having just upgraded from prettier 2.0.5 to 2.1.0. 
I have a `.vue` Single File Components with SASS style where I apply a mixin to a selector

For example, something like:
```
// Works with Prettier 2.0.5
<style lang="sass">
.hero
  @include background-centered
</style>
```

Was acceptable for Prettier 2.0.5, but now 2.1.0 suggests me to delete the newline and insert a semicolon at the end, like this:
```
// Fix suggested by prettier 2.1.0
<style lang="sass">
.hero @include background-centered;
</style>
```
This produces a Sass compilation error.

Using the mixin shorthand `+` also confuses Prettier when there are not other rules:
```
// Works with Prettier 2.0.5
<style lang="sass">
.hero
  +background-centered
</style>
```

Prettier will suggest this edit:
```
// Fix suggested by prettier 2.1.0
<style lang="sass" scoped>
.hero + background-centered;
</style>
```

When there are actual rules preceding or following, there are no problems:
```
// Works with Prettier 2.0.5 and Prettier 2.1.0
<style lang="sass">
.hero
  +background-centered

.another-selector
  margin: 0 auto
</style>
```

So the problem seems to be pulled up by having selectors with only mixins applied and no actual rules. As soon as the .sass file includes an actual CSS rule, having a selector with just a mixin is nice for Prettier, not before ^^

**Comment by thorn0** [comment]
It's a bug. Prettier should keep `style` blocks with unsupported `lang` as is.

**Comment by fisker** [comment]
I'll work on this
