### ISSUE TITLE
Potential Breaking Change in `resolveConfig`

### ISSUE THREAD

**Issue by ntotten** [prettier/prettier#7949]
It seems that 2.0 may have introduced an unintended breaking change in the `resolveConfig` function. This function is used in the Prettier VS Code extension here: https://github.com/prettier/prettier-vscode/blob/master/src/ConfigResolver.ts#L99

Since upgrading to 2.0 we are now seeing errors when trying to resolve configs:

```
Error: Cannot find module 'prettier-config-greenelab' from 'c:\Users\Vincent\Desktop\adage-frontend'
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
	at Function.n.resolve (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:15:584)
	at Object.transform (c:\Users\Vincent\.vscode\extensions\esbenp.prettier-vscode-4.0.0\node_modules\prettier\index.js:23283:40)
	at run (c:\Users\Vincent\.vscode\extensions\esbenp.prettier-vscode-4.0.0\node_modules\prettier\third-party.js:11472:51)
	at async cacheWrapper (c:\Users\Vincent\.vscode\extensions\esbenp.prettier-vscode-4.0.0\node_modules\prettier\third-party.js:11300:20)
	at async cacheWrapper (c:\Users\Vincent\.vscode\extensions\esbenp.prettier-vscode-4.0.0\node_modules\prettier\third-party.js:11300:20)
	at async cacheWrapper (c:\Users\Vincent\.vscode\extensions\esbenp.prettier-vscode-4.0.0\node_modules\prettier\third-party.js:11300:20)
	at async cacheWrapper (c:\Users\Vincent\.vscode\extensions\esbenp.prettier-vscode-4.0.0\node_modules\prettier\third-party.js:11300:20)
	at async cacheWrapper (c:\Users\Vincent\.vscode\extensions\esbenp.prettier-vscode-4.0.0\node_modules\prettier\third-party.js:11300:20)
	at async Explorer.search (c:\Users\Vincent\.vscode\extensions\esbenp.prettier-vscode-4.0.0\node_modules\prettier\third-party.js:11457:22)
	at async Promise.all (index 0)
```
 
For repro steps and more details see: https://github.com/prettier/prettier-vscode/issues/1289

One thing to note, is that everything behaves as expected from the CLI which is odd.

**Comment by ntotten** [comment]
@lipis Opened an issue in prettier repo to track.

**Comment by fisker** [comment]
@ntotten Can you try run `node -p "require('prettier-config-greenelab')"` in this  dir  'c:\Users\Vincent\Desktop\adage-frontend' ?

I  didn't see  this  package on  npm , please check if  your `package.json` in `prettier-config-greenelab` and  your project root  has `type :"module"

**Comment by fisker** [comment]
Anyway we should change this line https://github.com/prettier/prettier/blob/4ac088c139594af21657285791edcbc6968b2741/src/config/resolve-config.js#L27 to show the original message anyway, I think I break this. :simile:

**Comment by ntotten** [comment]
Running `node -p "require('prettier-config-greenelab')"` seems to work as expected. The module isn't in NPM, its just a sample the OP of our bug created, you can find it here: github.com/greenelab/prettier-config-greenelab

![image](https://user-images.githubusercontent.com/282782/78400336-7d08f400-75c4-11ea-9215-c1a353c81fb4.png)

**Comment by vincerubinetti** [comment]
Hi folks, I'm the one who originally posted the downstream issue on VSCode Prettier. That config is not on npm because I didn't feel like publishing and maintaining a package just for a small lint config file. You can install it right form the git repo:

https://github.com/greenelab/prettier-config-greenelab

**Comment by ntotten** [comment]
It looks like the issue is that `prettier` removed support for config for files with just the string content:

In `.prettierrc.yaml` this no longer works:

```
"prettier-config-greenelab"
```

However, this does work:
```
prettier: "prettier-config-greenelab"
```

I think as long as prettier returns a better error message and the breaking change is noted, this is probably okay - assuming it was deliberate.

**Comment by vincerubinetti** [comment]
@ntotten I just tried that, and it worked, even in VSCode Prettier v `4.0.0`.

Here is the relevant docs section that needs to be updated:
https://prettier.io/docs/en/configuration.html#sharing-configurations

**Comment by fisker** [comment]
No we didn't, I'll check it later.

**Comment by thorn0** [comment]
@fisker Looks like `require.resolve` doesn't work in VS Code extensions the way it works in Node 8.9.0+. `require.resolve.length` returns `1`.

**Comment by ntotten** [comment]
Ah, this is probably because the extension is webpacked.

The extension handles this in our module loader: https://github.com/prettier/prettier-vscode/blob/master/src/ModuleResolver.ts#L263-L265

**Comment by fisker** [comment]
but

```
prettier: "prettier-config-greenelab"
```

this  work ?  This also use `require.resolve`

**Comment by fisker** [comment]
@ntotten where did you put this `prettier: "prettier-config-greenelab"`?

**Comment by thorn0** [comment]
@fisker Are you sure? I thought `cosmiconfig` deals with that.

**Comment by fisker** [comment]
@thorn0 I'm sure, if it's in `package.json`.

**Comment by ntotten** [comment]
I think the reason that it seems to work when it is set to `prettier: "prettier-config-greenelab"` is because `resolveConfig` then just returns:

```
{ "prettier": "prettier-config-greenelab" }
```

Then the extension passes this config back to prettier and then prettier resolves the full config. However, in the case we pass just `"prettier-config-greenelab"` it looks like `resolveConfig` attempts to load the config from the module and should return the actually config value:

```
{ printWidth: 80,
  tabWidth: 2,
  useTabs: false,
  semi: true,
  singleQuote: true,
  quoteProps: 'consistent',
  jsxSingleQuote: true,
  trailingComma: 'none',
  bracketSpacing: true,
  jsxBracketSameLine: false,
  arrowParens: 'always',
  requirePragma: false,
  insertPragma: false,
  proseWrap: 'always',
  htmlWhitespaceSensitivity: 'css',
  endOfLine: 'lf' }
```

I am not sure why the module resolution seems to work in one case but not the other though.

**Comment by fisker** [comment]
Alright, I thought you put that in `package.json`, so should be the `require.resolve` problem, I misunderstood that.

**Comment by ntotten** [comment]
Seems cosmiconfig doesn't handle webpack: https://github.com/davidtheclark/cosmiconfig/issues/222

**Comment by thorn0** [comment]
@ntotten It doesn't look like your loader overrides `require.resolve`. Or am I wrong? The problem seems to be the fact that in Node 8.9.0+ `require.resolve` accepts a second argument, which Prettier 2.0 uses, but in the extension `require.resolve` seems to not support that.

**Comment by fisker** [comment]
It's not about `cosmiconfig`, it gives us the string, which is expected, we require it on our side.

**Comment by fisker** [comment]
I guess  everyone has  their own `require`? First `jest`, now `vscode`..

**Comment by ntotten** [comment]
The require is from `webpack`: https://webpack.js.org/api/module-methods/#requireresolve

But it doesn't look like it supports the options parameter.

**Comment by fisker** [comment]
No, there is only one argument.

**Comment by thorn0** [comment]
@ntotten I there a way to have the original `require.resolve` there? The loading of plugins relies on it too, not only configs.

**Comment by ntotten** [comment]
I am not entirely sure. This is getting deep into webpack and vscode extensions. The other thing I am a bit confused about is why this also happens when I am running the extension in debug mode - which doesn't get webpacked and should have the original `require.resolve`.

**Comment by ntotten** [comment]
Actually, i think we are on the wrong track. We should always be using the regular require.

```
      typeof __webpack_require__ === "function"
        ? __non_webpack_require__
        : require;
```

That will return the default global `require` regardless of if we are webpacked or not. See: https://webpack.js.org/api/module-variables/#__non_webpack_require__-webpack-specific

**Comment by fisker** [comment]
@ntotten Is there a way you can replace `require.resolve` with something like `resolve-from`.

**Comment by ntotten** [comment]
@fisker I could, but I would need some way to pass my resolver to prettier.

**Comment by ntotten** [comment]
It seems to be a known issue in VS Code. It is due to webpack's restriction on `require.resolve`. https://github.com/microsoft/vscode/issues/78894

**Comment by thorn0** [comment]
I have a fix: `require('module').createRequire(dir).resolve.length === 2`

**Comment by thorn0** [comment]
@ntotten Should we fix this on Prettier's side or in the extension (by passing a `require` instance created with `require('module').createRequire` in `ModuleResolver`)?

**Comment by ntotten** [comment]
@thorn0 It's up to you, given that I already have to deal with this in several places in the extension, I'm fine passing in an instance of require, but it also might be cleaner just to do it in `prettier` so there isn't any public API to deal with.

**Comment by thorn0** [comment]
Okay, I'm about to submit a PR.
