### ISSUE TITLE
TypeError: codeFrame.codeFrameColumns is not a function

### ISSUE THREAD

**Issue by josephfrazier** [prettier/prettier#1927]
Demo:

```bash
$ echo 'a.2' | prettier
stdin: TypeError: codeFrame.codeFrameColumns is not a function
    at Object.parse (/Users/josephfrazier/workspace/prettier/parser.js:23:35)
    at formatWithCursor (/Users/josephfrazier/workspace/prettier/index.js:59:22)
    at Object.formatWithCursor (/Users/josephfrazier/workspace/prettier/index.js:257:12)
    at format (/Users/josephfrazier/workspace/prettier/bin/prettier.js:207:19)
    at getStdin.then.input (/Users/josephfrazier/workspace/prettier/bin/prettier.js:274:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

This is related to https://github.com/prettier/prettier/pull/1902, as reverting 584bf4ecbfa191b3260c86ce78c960bd525463a6 fixes it (cc @SimenB).

EDIT: Once this is fixed, we can add an integration test to protect against regressions.

**Comment by josephfrazier** [comment]
Oops, I hadn't reinstalled my dependencies :(

**Comment by SimenB** [comment]
An integration test might be a good idea either way 😄

**Comment by vjeux** [comment]
You scared me for a sec, I thought i'd have to release 1.4.2 :p

**Comment by josephfrazier** [comment]
Heh, I should have written the supposedly-failing test and opened a PR with it. That way, I would have found out that it wasn't actually broken, and the test would have been written already :P
