### PR TITLE
HTML: Fix format on `style[lang="sass"]`

### LINKED ISSUE #9050: Prettier 2.1.0 and Sass rules with single mixin inclusion
Having just upgraded from prettier 2.0.5 to 2.1.0. 
I have a `.vue` Single File Components with SASS style where I apply a mixin to a selector

For example, something like:
```
// Works with Prettier 2.0.5
<style lang="sass">
.hero
  @include background-centered
</style>
```

Was acceptable for Prettier 2.0.5, but now 2.1.0 suggests me to delete the newline and insert a semicolon at the end, like this:
```
// Fix suggested by prettier 2.1.0
<style lang="sass">
.hero @include background-centered;
</style>
```
This produces a Sass compilation error.

Using the mixin shorthand `+` also confuses Prettier when there are not other rules:
```
// Works with Prettier 2.0.5
<style lang="sass">
.hero
  +background-centered
</style>
```

Prettier will suggest this edit:
```
// Fix suggested by prettier 2.1.0
<style lang="sass" scoped>
.hero + background-centered;
</style>
```

When there are actual rules preceding or following, there are no problems:
```
// Works with Prettier 2.0.5 and Prettier 2.1.0
<style lang="sass">
.hero
  +background-centered

.another-selector
  margin: 0 auto
</style>
```

So the problem seems to be pulled up by having selectors with only mixins applied and no actual rules. As soon as the .sass file includes an actual CSS rule, having a selector with just a mixin is nice for Prettier, not before ^^

### PR DESCRIPTION
**Pull request by fisker**
Fixes #9050

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

File: tests/html/multiparser/unknown/__snapshots__/jsfmt.spec.js.snap [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+<html lang="en">
+  <head>
+    <meta charset="UTF-8" />
+    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
+    <title>Document</title>
+  </head>
+  <body>
+    <style lang="unknown">
+      foo
+             bar
```
Comment (fisker) [inline tests/html/multiparser/unknown/__snapshots__/jsfmt.spec.js.snap:50]: Maybe we should keep the indention too?

@thorn0

Comment (thorn0) [reply tests/html/multiparser/unknown/__snapshots__/jsfmt.spec.js.snap:50]: Probably. It's safer.

Comment (evilebottnawi) [reply tests/html/multiparser/unknown/__snapshots__/jsfmt.spec.js.snap:50]: I think adding indentation for whole block is good idea

Comment (thorn0) [reply tests/html/multiparser/unknown/__snapshots__/jsfmt.spec.js.snap:50]: We don't know any style languages that can be broken by it, do we? So practically speaking, adding indentation is okay.

Comment (fisker) [reply tests/html/multiparser/unknown/__snapshots__/jsfmt.spec.js.snap:50]: Okay

File: tests/vue/multiparser/unknow.vue [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+
+<script type="unknown" lang="unknown">
+    foo
+          bar
+</script>
+
+<template lang="unknown">
+    foo
+          bar
+</template>
```
Comment (thorn0) [inline tests/vue/multiparser/unknow.vue:24]: Rename unknow.vue → unknown.vue?

Comment (fisker) [reply tests/vue/multiparser/unknow.vue:24]: Typo

**Comment by fisker** [comment]
Hey, guys.

I installed a new bot called [`prettifier`](https://www.prettifier.net/) on my fork today, it run Prettier on commit, feels good.

https://github.com/prettier/prettier/pull/9051/commits/58539a03e4cfde962fc9fb882bb59bb40707c915

**Review by thorn0 — APPROVED** [review]

**Comment by thorn0** [comment]
@fisker Looks good. The right URL is https://github.com/kevgo/prettifier What version of Prettier does it use? The one installed in the repo?

**Comment by fisker** [comment]
I don't know yet... Just installed about 5 hours.

File: tests/html/multiparser/unknown/__snapshots__/jsfmt.spec.js.snap [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+<html lang="en">
+<head>
+  <meta charset="UTF-8">
+  <meta name="viewport" content="width=device-width, initial-scale=1.0">
+  <title>Document</title>
+</head>
+<body>
+  <style lang="unknown">
+foo
+       bar
```
Comment (fisker) [inline tests/html/multiparser/unknown/__snapshots__/jsfmt.spec.js.snap:19]: One second, I need change this to valid css, because the parser might be `css` and it throws.

**Comment by fisker** [comment]
@thorn0 It seems it's not running the one installed in the repo

https://github.com/fisker/prettier/commits/test-prettifier

**Comment by fisker** [comment]
I'll uninstall it.

But, I found it because I was looking for similar bot, maybe we can build one?

File: tests/vue/multiparser/__snapshots__/jsfmt.spec.js.snap [hunk 4]
```diff
@@ -164,6 +164,78 @@ printWidth: 80
 ================================================================================
 `;
 
+exports[`unknown.vue format 1`] = `
+====================================options=====================================
+parsers: ["vue"]
+printWidth: 80
```
Comment (sosukesuzuki) [inline tests/vue/multiparser/__snapshots__/jsfmt.spec.js.snap:170]: Can you add tests for the case `--vue-indent-script-and-style` is `true`?

Comment (fisker) [reply tests/vue/multiparser/__snapshots__/jsfmt.spec.js.snap]: `embeddedLanguageFormatting: "off"` `vueIndentScriptAndStyle: true` tested

**Review by sosukesuzuki — APPROVED** [review]
Looks good

**Review by evilebottnawi — APPROVED** [review]

**Comment by thorn0** [comment]
@fisker As for the bot, a GitHub Action is a much more straightforward option for this. E.g. see https://driesvints.com/blog/code-style-formatting-with-github-actions
