### ISSUE TITLE
Can't run prod tests with yarn 1.0.x

### ISSUE THREAD

**Issue by suchipi** [prettier/prettier#2819]
As discovered in https://github.com/prettier/prettier/issues/2804#issuecomment-329346959, `yarn test --prod` passes the `--prod` argument to jest instead when using yarn >1.0.0, so the tests don't run correctly. I was able to run them by downgrading to yarn v0.28.4.

**Comment by vjeux** [comment]
Did you try `yarn --prod test`?

**Comment by suchipi** [comment]
That does:
```
$ yarn --prod test
yarn test v1.0.2
error No command specified.
info Commands available from binary scripts: acorn, babel, babel-doctor, babel-external-helpers, babel-node, babylon, cake, codecov, coffee, cross-env, cross-env-shell, errno, escodegen, esgenerate, eslint, esparse, esvalidate, handlebars, har-validator, jest, jest-runtime, js-yaml, jsesc, json5, loose-envify, markdown-toc, miller-rabin, mkdirp, node-pre-gyp, nopt, prettier, rc, regjsparser, remarkable, rimraf, rollup, sane, semver, sha.js, shjs, sshpk-conv, sshpk-sign, sshpk-verify, tsc, tsserver, uglifyjs, user-home, uuid, webpack, which
info Project commands
   - build
      node ./scripts/build/build.js
   - lint
      cross-env EFF_NO_LINK_RULES=true eslint . --format node_modules/eslint-friendly-formatter
   - test
      jest
   - test-integration
      jest tests_integration
   - toc
      node ./scripts/table-of-contents.js
error No command specified.
✨  Done in 6.72s.
```

What is the `--prod` flag supposed to do? Does it just set process.env.NODE_ENV or something?

**Comment by vjeux** [comment]
@azz ?

**Comment by vjeux** [comment]
What about

```
NODE_ENV=production yarn test
```

**Comment by suchipi** [comment]
That runs the tests, but the output doesn't make it obvious whether it's running against dist

**Comment by lydell** [comment]
Adding

```js
console.log("IS PRODCUTION?", isProduction);
```

here: https://github.com/prettier/prettier/blob/219acfe0f80218f73b28b8d11db46ac52de62592/tests_config/run_spec.js#L3

confirms that

```bash
NODE_ENV=production yarn test
```

works, because

```
IS PRODCUTION? true
```

is logged. And if I delete dist/ these errors show up:

```
Cannot find module '../dist/' from 'run_spec.js'
```

I'm wonder if the `--prod` flag has ever worked. Either way we should be able to simply update the instructions in build.js to say `NODE_ENV=production yarn test` instead.

**Comment by suchipi** [comment]
Thanks @lydell!

**Comment by azz** [comment]
`yarn run --prod test` seems to be the only way to get the `--prod` flag to work in 1.0.

**Comment by lydell** [comment]
@azz That works! Nice find. I think we'll stick with `NODE_ENV=production yarn test` now, though, since it is more explicit. I can't find any documentation on the `--prod`/`--production` flag, other than for the [install](https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-production-true-false) command.
