### PR TITLE
Reverts #7865, keeping class names on the same line

### PR DESCRIPTION
**Pull request by jlongster**
## Description

This reverts #7865 which introduced automatically breaking class names across multiple lines. This has introduced significant community churn, particularly in CSS frameworks like Tailwind where it's typical to have a lot of class names.

I think this was on overstep on Prettier's part. The consequence of breaking this line is large and there's not a strong enough reason for it. While these decisions are somewhat subjective, I still don't see strong arguments to implement this feature. It's too opinionated. It's a "nice" thing for people that want it, but it wreaks havoc on code for people that don't want it. Given that balance, I think we should remove it.

If we merge this PR and someone really wants class names to be formatted, look into suggestions like here: https://github.com/prettier/prettier/issues/10918#issuecomment-971055862. I think it'd be fine to simply break the class names across lines if there is newline in there. It's not fully reversable, but we have the same behavior for objects. I don't 100% love it all the time, but it is a clever technique that balances the tradeoffs between users. I think it'd be fine here even if I don't want that behavior for everything.

## Checklist

- [x] I’ve added tests to confirm my change works.
- [x] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

File: tests/format/html/attributes/__snapshots__/jsfmt.spec.js.snap [hunk 1]
```diff
@@ -253,29 +253,17 @@ printWidth: 80
 
 =====================================output=====================================
 <div
-  class="
-    ProviderMeasuresContainer__heading-row
-    d-flex
-    flex-column flex-lg-row
-    justify-content-start justify-content-lg-between
-    align-items-start align-items-lg-center
-  "
```
Comment (j-f1) [inline tests/format/html/attributes/__snapshots__/jsfmt.spec.js.snap:262]: Can you add this output as a new test input to make sure that existing code with line breaks in the `class` attribute continues to be formatted correctly?

Comment (jlongster-stripe) [reply tests/format/html/attributes/__snapshots__/jsfmt.spec.js.snap:262]: This PR does not implement the behavior where it keeps it if there is already a line break. So they will get collapsed. 

I just realized why I never noticed this behavior before: In JSX, we just keep the class name as it exactly. It seems like the JSX and HTML behavior should be exactly the same. We should just keep the class name as is, so that means that all existing users won't be effected.

Comment (jlongster) [reply tests/format/html/attributes/__snapshots__/jsfmt.spec.js.snap:262]: This PR does not implement the behavior where it keeps it if there is already a line break. So they will get collapsed.

I just realized why I never noticed this behavior before: In JSX, we just keep the class name as it exactly. It seems like the JSX and HTML behavior should be exactly the same. We should just keep the class name as is, so that means that all existing users won't be effected.

**Review by azz — APPROVED** [review]

File: tests/format/html/attributes/__snapshots__/jsfmt.spec.js.snap (hunk 1 above)
Comment (fisker) [reply tests/format/html/attributes/__snapshots__/jsfmt.spec.js.snap:262]: > In JSX, we just keep the class name as it exactly. It seems like the JSX and HTML behavior should be exactly the same. 

Formatting for class names in html was introduced in #7555  https://prettier.io/blog/2020/03/21/2.0.0.html#format-value-of-html-class-attribute-7555httpsgithubcomprettierprettierpull7555-by-fiskerhttpsgithubcomfisker

**Review by fisker — APPROVED** [review]
This will reopen #7863

**Review by sosukesuzuki — APPROVED** [review]

**Comment by AndrewBogdanovTSS** [comment]
I can say that this is super weird behavior. Is there any chance to have this available at least behind an option, something similar to  proseWrap? Maybe classWrap?

**Comment by alicercedigital** [comment]
Someone know how to solve this?
We need an formater to long classNames. There is a way to activate this without downgrade Prettier?

**Comment by AndrewBogdanovTSS** [comment]
@alicercedigital I don't think it's possible at the moment, but highly needed in my opinion
