### ISSUE TITLE
ERROR prettier.resolveConfig.sync is not a function

### ISSUE THREAD

**Issue by Crawk95** [prettier/prettier#15022]
**Environments:**

- Prettier Version: 3.0.0
- Running Prettier via:  CLI
- Runtime: NestJS
- Operating System: Ubuntu

**Steps to reproduce:**

updating to 3.0.0

**Expected behavior:** Lint should be works without error

**Actual behavior:**
After upgrading from 2.8.8 to 3.0.0 I receive this error

```
Oops! Something went wrong! :(

ESLint: 8.43.0

TypeError: prettier.resolveConfig.sync is not a function
Occurred while linting src/app.module.ts:1
Rule: "prettier/prettier"
```
After downgrade back to 2.8.8 it works

**Comment by auvred** [comment]
Hi, it seems that you need to update `eslint-plugin-prettier` to alpha version, you can find more info there: https://github.com/prettier/eslint-plugin-prettier/issues/562

**Comment by msalahz** [comment]
Had the same issue while integrating prettier with Eslint into a NextJS application

**Comment by Crawk95** [comment]
> Hi, it seems that you need to update `eslint-plugin-prettier` to alpha version, you can find more info there: [prettier/eslint-plugin-prettier#562](https://github.com/prettier/eslint-plugin-prettier/issues/562)

Works, thank you! When will be published stable version with this changes?

**Comment by Crawk95** [comment]
> Had the same issue while integrating prettier with Eslint into a NextJS application

update eslint-plugin-prettier to alpha version

**Comment by Kaweees** [comment]
Howdy everyone, solution to this bug has been to do the following steps:
Update the `eslint-plugin-prettier` to alpha version in your `package.json`
"eslint-plugin-prettier": "^5.0.0-alpha.1",
Then you should reinstall your project dependencies
```rm -rf node_modules
npm install```
Then it worked

**Comment by sosukesuzuki** [comment]
This is a eslint-plugin-prettier's problem. So close this.

**Comment by ChristopheLav** [comment]
Hi @sosukesuzuki, the [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) is under prettier organization. Why not to sync the releases to ensure the "own" ecosystem is compatible ? The experience would be much nicer.

**Comment by websitevirtuoso** [comment]
I tried to use 
"eslint-plugin-prettier": "^5.0.0-alpha.2"
but it doesn't work for me. I have vite latest version + vuejs

**Comment by auvred** [comment]
`prettier.resolveConfig.sync` is commonly used by plugins, that don't support new prettier@3 async api, so this is probably issue of the prettier plugin

**Comment by websitevirtuoso** [comment]
OK I think I found that plugin
stylelint-prettier
or 
vite-plugin-stylelint
has to be updated

**Comment by auvred** [comment]
There is already issue for v3 support https://github.com/prettier/stylelint-prettier/issues/298

**Comment by websitevirtuoso** [comment]
I see. thanks for provided info
