### ISSUE TITLE
Bug: Cr(...).__exportStar is not a function

### ISSUE THREAD

**Issue by bodinsamuel** [prettier/prettier#12493]
**Environments:**

- Prettier Version: 2.6.0
- Running Prettier via: Node.js API, Browser API
- Runtime: Node 16.14.0
- Operating System: macOS

**Context**

Since 2.6.0, it seems Prettier can not be bundled with webpack, it throws this error `Received: "Cr(...).__exportStar is not a function"` (not at compile time but usage time).
I saw there was a change to esbuild, might be that?

**Steps to reproduce:**

Hard to say at this point I'm just reporting as I found out.

```ts
import babel from 'prettier/parser-babel';
import prettier from 'prettier/standalone';

// Providing this plugin is required in order for prettier to use 'babel' as parser.
const prettierPlugins = [babel];

export function prettify(code: string): string {
  return prettier
    .format(code, { parser: 'babel', plugins: prettierPlugins })
    .trim();
}
``` 

- webpack.config.js
```js
const path = require('path');

const { CleanWebpackPlugin } = require('clean-webpack-plugin');
const TerserPlugin = require('terser-webpack-plugin');
const { ProvidePlugin } = require('webpack');

const resolvedExtensions = ['.js', '.jsx', '.ts', '.tsx'];

module.exports = function pack(env, options) {
  const mode = options.mode || 'development';
  const production = mode === 'production';

  // See what changes what here: https://webpack.js.org/configuration/devtool/#devtool
  let devtool = 'eval-cheap-module-source-map';
  if (production) {
    devtool = 'cheap-source-map';
  } else if (process.env.CI) {
    devtool = undefined;
  }

  return {
    target: 'web',
    mode,
    devtool,
    entry: {
      extractor: path.resolve(__dirname, 'src', 'extractor', 'index.ts'),
      converter: path.resolve(__dirname, 'src', 'converter', 'index.ts'),
    },
    output: {
      path: path.resolve(__dirname, 'build'),
      filename: '[name].js',
      libraryTarget: 'umd',
      library: 'exported',
      globalObject: 'this',
    },
    module: {
      rules: [
        {
          test: /\.tsx?$/,
          exclude: /node_modules/,
          use: [
            {
              loader: 'babel-loader',
              options: {
                presets: [
                  [
                    '@babel/preset-env',
                    {
                      targets: {
                        browsers: ['last 2 versions'],
                      },
                    },
                  ],
                  [
                    '@babel/preset-typescript',
                    { isTSX: false, onlyRemoveTypeImports: true },
                  ],
                ],
                plugins: [
                  '@babel/plugin-proposal-object-rest-spread',
                  '@babel/plugin-proposal-class-properties',
                  '@babel/plugin-proposal-private-methods',
                  '@babel/plugin-proposal-private-property-in-object',
                  '@babel/plugin-proposal-optional-chaining',
                  '@babel/plugin-proposal-nullish-coalescing-operator',
                ],
                cacheDirectory: true,
                cacheCompression: false,
              },
            },
          ],
        },
      ],
    },
    resolve: {
      extensions: resolvedExtensions,
      modules: [path.resolve(__dirname, 'src'), 'node_modules'],
      fallback: {
        buffer: 'buffer',
        path: 'path-browserify',
        process: 'process/browser',
        url: 'core-js/stable/url',
        util: 'util',
        fs: false,
        tls: false,
        net: false,
        zlib: false,
        http: false,
        https: false,
        stream: false,
        crypto: false,
      },
    },
    plugins: [
      new CleanWebpackPlugin(),
      new ProvidePlugin({
        process: 'process/browser',
        Buffer: ['buffer', 'Buffer'],
        URL: 'core-js/stable/url',
      }),
    ],
    optimization: {
      minimize: production,
      minimizer: [
        new TerserPlugin({
          parallel: true,
          terserOptions: {
            /* eslint-disable camelcase */
            keep_classnames: true,
            keep_fnames: true,
            /* eslint-enable camelcase */
          },
        }),
      ],
    },
    stats: {
      assets: true,
      assetsSort: 'size',
      builtAt: false,
      cached: false,
      cachedAssets: false,
      children: false,
      chunks: false,
      colors: true,
      entrypoints: false,
      hash: false,
      loggingTrace: true,
      modules: false,
      version: false,
    },
    performance: {
      maxEntrypointSize: 920000,
      maxAssetSize: 920000,
    },
  };
};


**Expected behavior:**

**Actual behavior:**

**Comment by fisker** [comment]
Can you try replace these two files from #12485, and see if it fixes you problem?

- https://deploy-preview-12485--prettier.netlify.app/lib/standalone.js
- https://deploy-preview-12485--prettier.netlify.app/lib/parser-babale.js

**Comment by chassteel** [comment]
@fisker I had the same issue

`TypeError: s.__exportStar is not a function` 

Replacing those two files didn't make any difference.

**Comment by fisker** [comment]
It's fine, I can look into this later.

**Comment by fisker** [comment]
If you can simply `webpack.config.js`, that will be helpful.

**Comment by chassteel** [comment]
@fisker I take it you'd like me to post my webpack.config.js so here it is.  I'm using CRA.

- webpack.config.js

```
const path = require('path');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const WebpackRTLPlugin = require('webpack-rtl-plugin');
const FixStyleOnlyEntriesPlugin = require('webpack-fix-style-only-entries');

module.exports = {
  mode: 'development',
  entry: {
    theme: './src/assets/scss/theme.scss',
    user: './src/assets/scss/user.scss'
  },
  output: {
    path: path.resolve(__dirname, 'public/css')
  },
  plugins: [
    new FixStyleOnlyEntriesPlugin(),
    new MiniCssExtractPlugin({
      filename: '[name].min.css'
    }),
    new WebpackRTLPlugin({
      filename: '[name]-rtl.min.css',
      minify: true
    }),
    new CleanWebpackPlugin()
  ],
  devtool: 'source-map',
  module: {
    rules: [
      {
        test: /\.(sass|scss)$/,
        use: [
          {
            loader: MiniCssExtractPlugin.loader,
            options: {
              sourceMap: true
            }
          },
          {
            loader: 'css-loader',
            options: {
              sourceMap: true,
              url: false
            }
          },
          {
            loader: 'sass-loader',
            options: {
              sourceMap: true
            }
          }
        ]
      }
    ]
  }
};

```

**Comment by alexander-akait** [comment]
@chassteel Do you consume commonjs version? Can you provide code how you do it?

**Comment by chassteel** [comment]
Here's the import syntax:

`import prettier from 'prettier/standalone'`

Is that what you wanted?

**Comment by fisker** [comment]
I didn't notice you are not the one opens this issue.

**Comment by chassteel** [comment]
Sorry to jump in.  I was trying to be helpful.

**Comment by bodinsamuel** [comment]
@fisker I will try tomorrow, thanks a lot for helping out 🙏🏻

**Comment by bodinsamuel** [comment]
@fisker  Did not work entirely, I have a similar error but somewhere else: `Nb.__exportStar is not a function` maybe it's just an indirect import and since I have replaced them it's actually fixed.
Seems the correct direction at least ☺️

**Comment by fisker** [comment]
I haven't, it will great if you can fix our build script.

**Comment by recurser** [comment]
@fisker I'm having the same issue after upgrading to 2.6.0. In the Next.js build log it also says this, in case it's useful:

```
./node_modules/prettier/standalone.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

It doesn't give any line numbers unfortunately. I'm importing it with `import { format } from 'prettier/standalone'`

**Comment by fisker** [comment]
@recurser #12485 should be able to fix your problem.

**Comment by fisker** [comment]
Can someone try to replace `standalone.js` with this file https://deploy-preview-12506--prettier.netlify.app/lib/standalone.js?

**Comment by tiagoskaneta** [comment]
@fisker replacing `standalone.js ` with the provided file does fix the issue for me.

**Comment by recurser** [comment]
@fisker apologies for the delay - that file doesn't seem to fix the issue for me. See [screenshot](https://user-images.githubusercontent.com/96322/159606558-1c51fdbc-2297-4a9d-baba-e3db532d1d2f.png). The app is actually [public](https://github.com/recurser/string-is) if you want to try it out yourself.

**Comment by fisker** [comment]
@recurser Thanks for your feedback.

**Comment by fisker** [comment]
@recurser Which file did you try?

**Comment by recurser** [comment]
@fisker this one:

> Can someone please try to replace standalone.js with this file https://deploy-preview-12506--prettier.netlify.app/lib/standalone.js?

It looks like something was caching though - if I blow away the entire repo, re-clone and rebuild, then your fix works 🎉  sorry for the confusion! 

In case you want to reproduce it:

```
git clone git@github.com:recurser/string-is.git
cd string-is
git checkout dependabot/npm_and_yarn/prettier-2.6.0
yarn install
yarn build
yarn start
open http://localhost:3000

# Broken 👎

cd ../
rm -Rf string-is
git clone git@github.com:recurser/string-is.git
cd string-is
git checkout dependabot/npm_and_yarn/prettier-2.6.0
yarn install
curl https://deploy-preview-12506--prettier.netlify.app/lib/standalone.js -o node_modules/prettier/standalone.js
yarn build
yarn start
open http://localhost:3000

# Fixed 👍
```

**Comment by fisker** [comment]
@recurser Thank you! I was about to test..

**Comment by fisker** [comment]
I believe #12511 should fix your problems.

To test it, replace your `node_modules/prettier/standalone.js` with this file https://deploy-preview-12511--prettier.netlify.app/lib/standalone.js

Welcome to feedback.

**Comment by recurser** [comment]
> To test it, replace your node_modules/prettier/standalone.js with this file https://deploy-preview-12511--prettier.netlify.app/lib/standalone.js

@fisker that works for me 🎉

**Comment by bodinsamuel** [comment]
Amazing, thanks a lot for looking into it ❤️

**Comment by fisker** [comment]
@brianzinn I can't help without details.

**Comment by brianzinn** [comment]
@fisker that was just to indicate that more files may be needed.  i brought in 'parser-typescript' from that netlify deploy and then it was working.  May have been due to gatsby caching, but is currently working.  Thanks for publishing the preview.

**Comment by sosukesuzuki** [comment]
I start to release 2.6.1. /cc @fisker

**Comment by fisker** [comment]
Sorry, didn't see this.

**Comment by sosukesuzuki** [comment]
Okay, my release script has been rejected by diff between local and remote. But no problem. I'll try to release again.

**Comment by sosukesuzuki** [comment]
done

**Comment by recurser** [comment]
@fisker I've upgraded to v2.6.1 and all works well - appreciate the quick work here! 👏
